name: "gail-issue-labeler"
description: "Label new issues using LLMs with gail"
author: 'Anthony Green'

inputs:
  llm_api_key:
    description: "OpenAI API key for GAIL"
    required: true

  github_token:
    description: "GitHub token for API calls"
    required: true

permissions:
  issues: write

runs:
  using: "composite"

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download latest GAIL release
      id: download-gail
      shell: bash
      run: |
        # fetch latest release metadata
        LATEST=$(curl -s https://api.github.com/repos/atgreen/gail/releases/latest)
        # pull out the URL for the linux binary
        URL=$(echo "$LATEST" \
          | jq -r '.assets[]
                    | select(.name == "gail-linux-x86_64")
                    | .browser_download_url')
        wget "$URL" -O gail-linux-x86_64
        chmod +x gail-linux-x86_64
        # expose it to subsequent steps
        echo "GAIL_PATH=$(pwd)/gail-linux-x86_64" >> $GITHUB_ENV

    - name: Run GAIL on the new issue
      shell: bash
      run: |
        cat <<EOF > action-issue.txt
        Issue title: ${{ github.event.issue.title }}
        Issue number: ${{ github.event.issue.number }}
        Issue body:
        ${{ github.event.issue.body }}
        EOF

        # invoke GAIL
        ${{ env.GAIL_PATH }} \
          --action "${{ github.repository_owner }}" \
                   "${{ github.event.repository.name }}" \
          < action-issue.txt
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        OPENAI_KEY: ${{ inputs.llm_api_key }}
