name: Generate Action Docs

on:
  push:
    branches: ["master"]

jobs:
  doc:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - uses: pndurette/gh-actions-auto-docs@v1
